project: PROJECT
region: us-central1
zones:
- us-central1-a
- us-central1-b
- us-central1-f

gatekeeper:
  enabled: true
  image:
    repository: us.gcr.io/PROJECT/isidro/gatekeeper
    tag: latest

repeater:
  enabled: true
  image:
    repository: us.gcr.io/PROJECT/isidro/repeater
    tag: latest

responder:
  enabled: true
  image:
    repository: us.gcr.io/PROJECT/isidro/responder
    tag: latest

deployer:
  github:
    enabled: true
    image:
      repository: us.gcr.io/PROJECT/isidro/deployer/github
      tag: latest
    token: "1234567890"

orchestration:
  enabled: true
  greeting: "Hello!"
  image:
    repository: us.gcr.io/PROJECT/isidro/orchestration
    tag: latest

policyAgent:
  enabled: true
  image:
    repository: openpolicyagent/opa
    tag: 0.33.1

keywords:
  enabled: true
  image:
    repository: us.gcr.io/PROJECT/isidro/keywords
    tag: latest

tasks:
  enabled: true
  image:
    repository: us.gcr.io/PROJECT/isidro/tasks
    tag: latest

rabbitmq:
  enabled: true
  global:
    storageClass: isidro-storage
  auth:
    password: "1234567890"
    erlangCookie: "1234567890"
  podLabels:
    app: rabbitmq
    sidecar.istio.io/inject: "true"
    istio.io/rev: "asm-managed-rapid"
  persistence:
    storageClass: isidro-storage
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
          "users": [
            {
              "name": "isidro",
              "password": "isidro",
              "tags": "administrator"
            }
          ],
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "permissions": [
            {
              "user": "isidro",
              "vhost": "/",
              "configure": ".*",
              "write": ".*",
              "read": ".*"
            },
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json
    loopback_users.isidro = false

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
  master:
    podLabels:
      app: redis-master
      sidecar.istio.io/inject: "true"
      istio.io/rev: "asm-managed-rapid"
    resources: {}

mattermost:
  enabled: true
  domain: isidro.example.com
  accessToken: "1234567890"
  verificationToken: "1234567890"

slack:
  enabled: false
  verificationToken: "1234567890"
  oauthToken: "1234567890"