apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: isidro
  namespace: configconnector-resources
spec:
  name: "{{ .Values.isidro.domain }}."
  type: A
  ttl: 300
  managedZoneRef:
    external: "{{ .Values.dns.zone }}"
  rrdatasRefs:
  - name: isidro
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: isidro
  namespace: configconnector-resources
spec:
  location: global
  resourceID: isidro
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: mattermost
  namespace: configconnector-resources
spec:
  name: "{{ .Values.mattermost.domain }}."
  type: A
  ttl: 300
  managedZoneRef:
    external: "{{ .Values.dns.zone }}"
  rrdatasRefs:
  - name: mattermost
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: mattermost
  namespace: configconnector-resources
spec:
  location: global
  resourceID: mattermost