---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mattermost
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mattermost
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          istio: ingressgateway
    - namespaceSelector: {}
  egress:
  - {}