{{ if eq .Values.mongodb.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: orchestration
  egress:
  - {}
{{ end }}