apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: orchestration
spec:
  selector:
    matchLabels:
      app: orchestration
  endpoints:
  - port: 80
    interval: 30s
    timeout: 10s