{{ if eq .Values.rabbitmq.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq
spec:
  podSelector:
    matchLabels:
      app: rabbitmq
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - {}
  egress:
  - {}
{{ end }}