---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis
spec:
  podSelector:
    matchLabels:
      app: redis-master
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - {}
  egress:
  - {}