{{ if eq .Values.mcs.enabled true }}
---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: mattermost
spec:
  template:
    spec:
      selector:
        app.kubernetes.io/name: mattermost
      ports:
      - name: web
        protocol: TCP
        port: 8065
        targetPort: 8065
---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: gatekeeper
spec:
  template:
    spec:
      selector:
        app: gatekeeper
      ports:
      - name: api
        protocol: TCP
        port: 80
        targetPort: 80
{{ end }}