---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracing-microservice
  annotations:
    iam.gke.io/gcp-service-account: isidro-tracing-microservices@{{ .Values.project }}.iam.gserviceaccount.com