apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: isidro
  namespace: config-connector-resources
spec:
  name: "ISIDRO_DOMAIN."
  type: A
  ttl: 300
  managedZoneRef:
    external: "DNS_ZONE_NAME"
  rrdatasRefs:
  - name: isidro
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: isidro
  namespace: config-connector-resources
spec:
  location: global
  resourceID: isidro
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: mattermost
  namespace: config-connector-resources
spec:
  name: "MATTERMOST_DOMAIN."
  type: A
  ttl: 300
  managedZoneRef:
    external: "DNS_ZONE_NAME"
  rrdatasRefs:
  - name: mattermost
    kind: ComputeAddress
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: mattermost
  namespace: config-connector-resources
spec:
  location: global
  resourceID: mattermost